USE dcasedb;

DELETE FROM NodeLink;
DELETE FROM ArgumentBranch;
DELETE FROM Commit;
DELETE FROM Context;
DELETE FROM DBNode;
DELETE FROM Argument;
DELETE FROM Branch;
ALTER TABLE Branch         AUTO_INCREMENT = 1;
ALTER TABLE ArgumentBranch AUTO_INCREMENT = 1;
ALTER TABLE Argument       AUTO_INCREMENT = 1;
ALTER TABLE NodeLink       AUTO_INCREMENT = 1;
ALTER TABLE Commit         AUTO_INCREMENT = 1;
ALTER TABLE DBNode         AUTO_INCREMENT = 1;
ALTER TABLE Context        AUTO_INCREMENT = 1;
